---
$schemaver: '2.0'
repo_url: https://github.com/byu-oit/byu-jwt-python
software:
  - name: byu-jwt-python
    type: Library
    aliases:
    short_description: A python JWT validator that does all the BYU specific stuff
        as well.
    assignment_group: gro:AD-Student Life Applications
    notes:
    maintained_by:
      - pauldeden
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: https://github.com/byu-oit/byu-jwt-python
        swagger_urls:
    microservice: false
    technologies_used:
      - Python
    stages:
        production:
            urls:
                product_page: https://github.com/byu-oit/byu-jwt-python
                physical_url:
                virtual_url:
            hosting_location:
            aws_account:
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
    tags:
        data-sensitivity: public
        team: AD-Student Life Applications
        app: byu-jwt-python
