---
$schemaver: '2.0'
repo_url: https://github.com/byu-oit/byu-jwt-python
software:
  - name: byu-jwt-python
    type: Library
    aliases:
    short_description: A python JWT validator that does all the BYU specific stuff
        as well.
    assignment_group: gro:AD-Student Life Applications
    notes:
    maintained_by:
      - pauldeden
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: https://github.com/byu-oit/byu-jwt-python
    microservice: false
    technologies_used:
      - Python
    stages:
        production:
            urls:
                product_page: https://github.com/byu-oit/byu-jwt-python
            hosting_location: Other
            relationships:
                supports:
                    software:
                    service:
    tags:
        data-sensitivity: public
        team: AD-Student Life Applications
        app: byu-jwt-python
