$schemaver: '2.0'
repo_url: https://github.com/byu-oit/byu-jwt-python
software:
  - aliases:
    assignment_group: gro:AD-Student Life Applications
    ddd:
      business_domain:
      context_map_url:
      ubiquitous_language_url:
    developed_by_byu: true
    links:
      system_documentation_url: https://github.com/byu-oit/byu-jwt-python
    maintained_by:
      - pauldeden
    microservice: false
    name: byu-jwt-python
    notes:
    short_description: A python JWT validator that does all the BYU specific stuff
      as well.
    stages:
      production:
        hosting_location: Other
        relationships:
          supports:
            service:
            software:
        urls:
          product_page: https://github.com/byu-oit/byu-jwt-python
    tags:
      app: byu-jwt-python
      data-sensitivity: public
      team: AD-Student Life Applications
    technologies_used:
      - Python
      - AWS CodeBuild
      - Handel-Codepipeline
      - AWS CodePipeline
    type: Library
