version: 0.2

env:
  parameter-store:
    PYPI_USER: byu-jwt-python.pypiuser
    PYPI_PASS: byu-jwt-python.pypipass

phases:
  install:
    commands:
      - pip install poetry
      - poetry install
  pre_build:
    commands:
      - poetry run pytest -vvv
  build:
    commands:
      - poetry build
      - poetry publish -u $PYPI_USER -p $PYPI_PASS
artifacts:
  files:
    - ./**/*
  