version: 0.2

env:
  parameter-store:
    PYPI_USER: byu-jwt-python.prd.pypiuser
    PYPI_PASS: byu-jwt-python.prd.pypipass

phases:
  install:
    commands:
      - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - poetry install
  pre_build:
    commands:
      - poetry run pytest -vvv
  build:
    commands:
      - poetry build
      - poetry publish -u $PYPI_USER -p $PYPI_PASS
artifacts:
  files:
    - ./**/*
  